#language: node_js
#node_js:
#    - "8"
#    - "10"
#    - "12"
#addons:
#    chrome: stable
#sudo: required
#before_script:
#    - "sudo chown root /opt/google/chrome/chrome-sandbox"
#    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"


language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm ci
script:
  - yarn docs:build # npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  keep_history: true
  on:
    branch: master